name: ETL pipeline demo

on:
  push:
    branches:
      - main

jobs:
  extract-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: python version
        run: python --version

      - name: run extract.py
        run: python .github/workflows/extract.py

  transform-job:
    runs-on: ubuntu-latest
    needs: extract-job

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run transform.py
        run: python .github/workflows/transform.py

  load-job:
    runs-on: ubuntu-latest
    needs: transform-job

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run load.py
        run: python .github/workflows/load.py
